const defaultProducts = [
  { nombre: 'Audifonos Bluetooth', precio: 399, descripcion: 'Audifonos inalambricos con conexion Bluetooth', categoria: 'Electronica', stock: 25, activo: true },
  { nombre: 'Mouse inalambrico', precio: 249, descripcion: 'Mouse optico inalambrico para computadora', categoria: 'Electronica', stock: 40, activo: true },
  { nombre: 'Teclado mecanico', precio: 899, descripcion: 'Teclado mecanico con iluminacion RGB', categoria: 'Electronica', stock: 15, activo: true },
  { nombre: 'Memoria USB 64GB', precio: 199, descripcion: 'Memoria USB de alta velocidad 64GB', categoria: 'Electronica', stock: 50, activo: true },
  { nombre: 'Bocina Bluetooth', precio: 499, descripcion: 'Bocina portatil con conexion Bluetooth', categoria: 'Electronica', stock: 30, activo: true },
  { nombre: 'Cable USB-C', precio: 120, descripcion: 'Cable de carga rapida USB tipo C', categoria: 'Electronica', stock: 60, activo: true },
  { nombre: 'Soporte para laptop', precio: 350, descripcion: 'Soporte ergonomico para computadora portatil', categoria: 'Accesorios', stock: 20, activo: true },
  { nombre: 'Power Bank 10000mAh', precio: 450, descripcion: 'Bateria portatil para cargar dispositivos moviles', categoria: 'Electronica', stock: 35, activo: true },
  { nombre: 'Funda para celular', precio: 150, descripcion: 'Funda protectora para smartphone', categoria: 'Accesorios', stock: 70, activo: true },
  { nombre: 'Protector de pantalla', precio: 100, descripcion: 'Protector de vidrio templado para celular', categoria: 'Accesorios', stock: 80, activo: true },
  { nombre: 'Soporte para celular', precio: 180, descripcion: 'Base ajustable para sostener smartphone', categoria: 'Accesorios', stock: 45, activo: true },
  { nombre: 'Adaptador HDMI', precio: 220, descripcion: 'Adaptador para conectar dispositivos HDMI', categoria: 'Electronica', stock: 25, activo: true },
  { nombre: 'Hub USB 4 puertos', precio: 260, descripcion: 'Expansor USB con cuatro puertos', categoria: 'Electronica', stock: 20, activo: true },
  { nombre: 'Lampara LED escritorio', precio: 300, descripcion: 'Lampara LED con luz ajustable para escritorio', categoria: 'Hogar', stock: 18, activo: true },
  { nombre: 'Reloj despertador digital', precio: 280, descripcion: 'Reloj digital con alarma y luz LED', categoria: 'Hogar', stock: 22, activo: true },
  { nombre: 'Botella termica', precio: 210, descripcion: 'Botella de acero inoxidable para bebidas', categoria: 'Hogar', stock: 30, activo: true },
  { nombre: 'Difusor de aromas', precio: 350, descripcion: 'Difusor electrico para aceites esenciales', categoria: 'Hogar', stock: 15, activo: true },
  { nombre: 'Juego de tazas', precio: 320, descripcion: 'Set de 4 tazas de ceramica', categoria: 'Hogar', stock: 20, activo: true },
  { nombre: 'Almohada ergonomica', precio: 450, descripcion: 'Almohada disenada para mejorar postura al dormir', categoria: 'Hogar', stock: 12, activo: true },
  { nombre: 'Cuaderno profesional', precio: 90, descripcion: 'Cuaderno tamano profesional 100 hojas', categoria: 'Papeleria', stock: 60, activo: true },
  { nombre: 'Mochila escolar', precio: 550, descripcion: 'Mochila resistente con varios compartimentos', categoria: 'Papeleria', stock: 25, activo: true },
  { nombre: 'Calculadora cientifica', precio: 420, descripcion: 'Calculadora cientifica para estudiantes', categoria: 'Papeleria', stock: 18, activo: true },
  { nombre: 'Plumas gel paquete', precio: 80, descripcion: 'Paquete de 5 plumas de tinta gel', categoria: 'Papeleria', stock: 75, activo: true },
  { nombre: 'Agenda 2026', precio: 160, descripcion: 'Agenda organizadora para el ano 2026', categoria: 'Papeleria', stock: 40, activo: true },
  { nombre: 'Mouse gamer RGB', precio: 650, descripcion: 'Mouse gamer con iluminacion RGB y alta precision', categoria: 'Gaming', stock: 15, activo: true },
  { nombre: 'Teclado gamer RGB', precio: 950, descripcion: 'Teclado gamer mecanico con iluminacion RGB', categoria: 'Gaming', stock: 10, activo: true },
  { nombre: 'Audifonos gamer', precio: 780, descripcion: 'Audifonos con microfono para videojuegos', categoria: 'Gaming', stock: 14, activo: true },
  { nombre: 'Control para PC', precio: 690, descripcion: 'Control compatible con computadora y juegos', categoria: 'Gaming', stock: 12, activo: true },
  { nombre: 'Tapete gamer', precio: 300, descripcion: 'Tapete grande para mouse gamer', categoria: 'Gaming', stock: 20, activo: true },
  { nombre: 'Soporte para control', precio: 200, descripcion: 'Base organizadora para control de videojuegos', categoria: 'Gaming', stock: 18, activo: true }
];

module.exports = defaultProducts;