INSERT INTO productos (id, nombre, precio, descripcion, categoria, stock, activo)
VALUES
  (1, 'Audífonos Bluetooth', 399, 'Audífonos inalámbricos con conexión Bluetooth', 'Electrónica', 25, TRUE),
  (2, 'Mouse inalámbrico', 249, 'Mouse óptico inalámbrico para computadora', 'Electrónica', 40, TRUE),
  (3, 'Teclado mecánico', 899, 'Teclado mecánico con iluminación RGB', 'Electrónica', 15, TRUE),
  (4, 'Memoria USB 64GB', 199, 'Memoria USB de alta velocidad 64GB', 'Electrónica', 50, TRUE),
  (5, 'Bocina Bluetooth', 499, 'Bocina portátil con conexión Bluetooth', 'Electrónica', 30, TRUE),
  (6, 'Cable USB-C', 120, 'Cable de carga rápida USB tipo C', 'Electrónica', 60, TRUE),
  (7, 'Soporte para laptop', 350, 'Soporte ergonómico para computadora portátil', 'Accesorios', 20, TRUE),
  (8, 'Power Bank 10000mAh', 450, 'Batería portátil para cargar dispositivos móviles', 'Electrónica', 35, TRUE),
  (9, 'Funda para celular', 150, 'Funda protectora para smartphone', 'Accesorios', 70, TRUE),
  (10, 'Protector de pantalla', 100, 'Protector de vidrio templado para celular', 'Accesorios', 80, TRUE),
  (11, 'Soporte para celular', 180, 'Base ajustable para sostener smartphone', 'Accesorios', 45, TRUE),
  (12, 'Adaptador HDMI', 220, 'Adaptador para conectar dispositivos HDMI', 'Electrónica', 25, TRUE),
  (13, 'Hub USB 4 puertos', 260, 'Expansor USB con cuatro puertos', 'Electrónica', 20, TRUE),
  (14, 'Lámpara LED escritorio', 300, 'Lámpara LED con luz ajustable para escritorio', 'Hogar', 18, TRUE),
  (15, 'Reloj despertador digital', 280, 'Reloj digital con alarma y luz LED', 'Hogar', 22, TRUE),
  (16, 'Botella térmica', 210, 'Botella de acero inoxidable para bebidas', 'Hogar', 30, TRUE),
  (17, 'Difusor de aromas', 350, 'Difusor eléctrico para aceites esenciales', 'Hogar', 15, TRUE),
  (18, 'Juego de tazas', 320, 'Set de 4 tazas de cerámica', 'Hogar', 20, TRUE),
  (19, 'Almohada ergonómica', 450, 'Almohada diseñada para mejorar postura al dormir', 'Hogar', 12, TRUE),
  (20, 'Cuaderno profesional', 90, 'Cuaderno tamaño profesional 100 hojas', 'Papelería', 60, TRUE),
  (21, 'Mochila escolar', 550, 'Mochila resistente con varios compartimentos', 'Papelería', 25, TRUE),
  (22, 'Calculadora científica', 420, 'Calculadora científica para estudiantes', 'Papelería', 18, TRUE),
  (23, 'Plumas gel paquete', 80, 'Paquete de 5 plumas de tinta gel', 'Papelería', 75, TRUE),
  (24, 'Agenda 2026', 160, 'Agenda organizadora para el año 2026', 'Papelería', 40, TRUE),
  (25, 'Mouse gamer RGB', 650, 'Mouse gamer con iluminación RGB y alta precisión', 'Gaming', 15, TRUE),
  (26, 'Teclado gamer RGB', 950, 'Teclado gamer mecánico con iluminación RGB', 'Gaming', 10, TRUE),
  (27, 'Audífonos gamer', 780, 'Audífonos con micrófono para videojuegos', 'Gaming', 14, TRUE),
  (28, 'Control para PC', 690, 'Control compatible con computadora y juegos', 'Gaming', 12, TRUE),
  (29, 'Tapete gamer', 300, 'Tapete grande para mouse gamer', 'Gaming', 20, TRUE),
  (30, 'Soporte para control', 200, 'Base organizadora para control de videojuegos', 'Gaming', 18, TRUE),
  (31, 'Bocina inteligente Lite', 649, 'Bocina inteligente compacta con asistente de voz y conectividad Bluetooth', 'Electrónica', 24, TRUE),
  (32, 'Bocina inteligente Plus', 739, 'Bocina inteligente con mejor potencia de audio y control por voz', 'Electrónica', 22, TRUE),
  (33, 'Bocina inteligente Pro', 829, 'Bocina inteligente para hogar con sonido envolvente y conexión WiFi', 'Electrónica', 20, TRUE),
  (34, 'Bocina inteligente Max', 929, 'Bocina inteligente de alto rendimiento para espacios medianos', 'Electrónica', 18, TRUE),
  (35, 'Bocina inteligente X', 999, 'Bocina inteligente premium con audio mejorado y diseño moderno', 'Electrónica', 16, TRUE),
  (36, 'Webcam HD Lite', 529, 'Webcam HD para videollamadas y clases en línea', 'Electrónica', 26, TRUE),
  (37, 'Webcam HD Plus', 619, 'Webcam HD con mejor nitidez y micrófono integrado', 'Electrónica', 24, TRUE),
  (38, 'Webcam HD Pro', 709, 'Webcam Full HD con enfoque automático para oficina remota', 'Electrónica', 22, TRUE),
  (39, 'Webcam HD Max', 799, 'Webcam avanzada para streaming y reuniones profesionales', 'Electrónica', 18, TRUE),
  (40, 'Webcam HD X', 889, 'Webcam de alta definición con lente optimizada para baja luz', 'Electrónica', 16, TRUE),
  (41, 'Router WiFi Lite', 899, 'Router inalámbrico para mejorar la cobertura de internet en casa', 'Electrónica', 20, TRUE),
  (42, 'Router WiFi Plus', 999, 'Router inalámbrico con doble banda para conexión estable', 'Electrónica', 18, TRUE),
  (43, 'Router WiFi Pro', 1129, 'Router WiFi con mejor alcance para oficina y hogar conectado', 'Electrónica', 16, TRUE),
  (44, 'Router WiFi Max', 1269, 'Router de alto desempeño para múltiples dispositivos simultáneos', 'Electrónica', 14, TRUE),
  (45, 'Router WiFi X', 1399, 'Router premium con administración avanzada de red', 'Electrónica', 12, TRUE),
  (46, 'Monitor LED 24 Lite', 2499, 'Monitor LED de 24 pulgadas para escritorio y productividad diaria', 'Electrónica', 14, TRUE),
  (47, 'Monitor LED 24 Plus', 2649, 'Monitor LED con mejor brillo y reproducción de color', 'Electrónica', 12, TRUE),
  (48, 'Monitor LED 24 Pro', 2799, 'Monitor de 24 pulgadas ideal para trabajo profesional y estudio', 'Electrónica', 10, TRUE),
  (49, 'Monitor LED 24 Max', 2949, 'Monitor LED con panel optimizado para jornadas extensas', 'Electrónica', 9, TRUE),
  (50, 'Monitor LED 24 X', 3099, 'Monitor premium con acabado moderno y mejor contraste', 'Electrónica', 8, TRUE),
  (51, 'SSD externo 500GB Lite', 899, 'Unidad SSD externa de 500GB para respaldo y movilidad', 'Electrónica', 22, TRUE),
  (52, 'SSD externo 500GB Plus', 979, 'Unidad SSD externa rápida para transferencia de archivos', 'Electrónica', 20, TRUE),
  (53, 'SSD externo 500GB Pro', 1069, 'SSD portátil con mejor velocidad y construcción resistente', 'Electrónica', 18, TRUE),
  (54, 'SSD externo 500GB Max', 1149, 'Unidad de almacenamiento externo para trabajo intensivo', 'Electrónica', 16, TRUE),
  (55, 'SSD externo 500GB X', 1239, 'SSD externo premium para uso profesional y personal', 'Electrónica', 14, TRUE),
  (56, 'Tablet 10 pulgadas Lite', 1899, 'Tablet de 10 pulgadas para estudio, lectura y entretenimiento', 'Electrónica', 18, TRUE),
  (57, 'Tablet 10 pulgadas Plus', 2049, 'Tablet con mejor capacidad para productividad cotidiana', 'Electrónica', 16, TRUE),
  (58, 'Tablet 10 pulgadas Pro', 2199, 'Tablet de alto rendimiento para trabajo y consumo multimedia', 'Electrónica', 14, TRUE),
  (59, 'Tablet 10 pulgadas Max', 2349, 'Tablet optimizada para videollamadas y aplicaciones exigentes', 'Electrónica', 12, TRUE),
  (60, 'Tablet 10 pulgadas X', 2499, 'Tablet premium con gran pantalla y respuesta fluida', 'Electrónica', 10, TRUE),
  (61, 'Micrófono USB Lite', 459, 'Micrófono USB para clases, oficina remota y llamadas', 'Electrónica', 28, TRUE),
  (62, 'Micrófono USB Plus', 539, 'Micrófono con mejor captura de voz para streaming básico', 'Electrónica', 24, TRUE),
  (63, 'Micrófono USB Pro', 619, 'Micrófono de condensador USB para grabación y podcast', 'Electrónica', 20, TRUE),
  (64, 'Micrófono USB Max', 709, 'Micrófono con mejor aislamiento de ruido para contenido digital', 'Electrónica', 18, TRUE),
  (65, 'Micrófono USB X', 789, 'Micrófono premium con audio claro para creadores y oficinas', 'Electrónica', 16, TRUE),
  (66, 'Smartwatch deportivo Lite', 999, 'Reloj inteligente deportivo para notificaciones y actividad física', 'Electrónica', 22, TRUE),
  (67, 'Smartwatch deportivo Plus', 1129, 'Smartwatch con mejor autonomía y monitoreo de salud', 'Electrónica', 20, TRUE),
  (68, 'Smartwatch deportivo Pro', 1269, 'Reloj inteligente con métricas avanzadas y diseño elegante', 'Electrónica', 18, TRUE),
  (69, 'Smartwatch deportivo Max', 1399, 'Smartwatch de alto desempeño para entrenamiento y productividad', 'Electrónica', 16, TRUE),
  (70, 'Smartwatch deportivo X', 1529, 'Reloj inteligente premium con conectividad mejorada', 'Electrónica', 14, TRUE),
  (71, 'Proyector portátil Lite', 2199, 'Proyector portátil para presentaciones y entretenimiento en casa', 'Electrónica', 12, TRUE),
  (72, 'Proyector portátil Plus', 2349, 'Proyector compacto con mejor brillo para espacios cerrados', 'Electrónica', 11, TRUE),
  (73, 'Proyector portátil Pro', 2499, 'Proyector con resolución mejorada para oficina y hogar', 'Electrónica', 10, TRUE),
  (74, 'Proyector portátil Max', 2649, 'Proyector de alto rendimiento para contenido multimedia', 'Electrónica', 9, TRUE),
  (75, 'Proyector portátil X', 2799, 'Proyector premium con conectividad avanzada y enfoque preciso', 'Electrónica', 8, TRUE),
  (76, 'Teclado inalámbrico Lite', 429, 'Teclado inalámbrico compacto para trabajo diario', 'Electrónica', 26, TRUE),
  (77, 'Teclado inalámbrico Plus', 519, 'Teclado inalámbrico con mejor ergonomía y batería duradera', 'Electrónica', 24, TRUE),
  (78, 'Teclado inalámbrico Pro', 609, 'Teclado inalámbrico para oficina y estaciones de trabajo', 'Electrónica', 22, TRUE),
  (79, 'Teclado inalámbrico Max', 689, 'Teclado con diseño premium y respuesta estable', 'Electrónica', 20, TRUE),
  (80, 'Teclado inalámbrico X', 769, 'Teclado inalámbrico avanzado para productividad continua', 'Electrónica', 18, TRUE),
  (81, 'Mouse ergonómico Lite', 319, 'Mouse ergonómico para reducir fatiga durante jornadas largas', 'Electrónica', 28, TRUE),
  (82, 'Mouse ergonómico Plus', 399, 'Mouse ergonómico con mejor agarre y desplazamiento preciso', 'Electrónica', 26, TRUE),
  (83, 'Mouse ergonómico Pro', 479, 'Mouse ergonómico ideal para trabajo intensivo y oficina', 'Electrónica', 24, TRUE),
  (84, 'Mouse ergonómico Max', 559, 'Mouse de alto rendimiento con diseño cómodo y estable', 'Electrónica', 22, TRUE),
  (85, 'Mouse ergonómico X', 639, 'Mouse premium con ergonomía avanzada y control preciso', 'Electrónica', 20, TRUE),
  (86, 'Lector de códigos Lite', 799, 'Lector de códigos para inventario y punto de venta', 'Electrónica', 18, TRUE),
  (87, 'Lector de códigos Plus', 899, 'Escáner de códigos con mejor velocidad de lectura', 'Electrónica', 16, TRUE),
  (88, 'Lector de códigos Pro', 999, 'Lector preciso para operaciones comerciales y almacén', 'Electrónica', 14, TRUE),
  (89, 'Lector de códigos Max', 1099, 'Escáner robusto para jornadas intensivas de operación', 'Electrónica', 12, TRUE),
  (90, 'Lector de códigos X', 1199, 'Lector premium con desempeño confiable y diseño resistente', 'Electrónica', 10, TRUE),
  (91, 'Impresora térmica Lite', 1399, 'Impresora térmica para tickets y comprobantes en mostrador', 'Electrónica', 14, TRUE),
  (92, 'Impresora térmica Plus', 1529, 'Impresora térmica con mayor velocidad de impresión', 'Electrónica', 12, TRUE),
  (93, 'Impresora térmica Pro', 1659, 'Impresora ideal para comercios con operación continua', 'Electrónica', 10, TRUE),
  (94, 'Impresora térmica Max', 1789, 'Impresora de alto desempeño para puntos de venta exigentes', 'Electrónica', 9, TRUE),
  (95, 'Impresora térmica X', 1919, 'Impresora premium con mejor estabilidad y respuesta rápida', 'Electrónica', 8, TRUE),
  (96, 'Cámara web 2K Lite', 899, 'Cámara web 2K para videollamadas con imagen más definida', 'Electrónica', 18, TRUE),
  (97, 'Cámara web 2K Plus', 999, 'Cámara web con mejor detalle para oficina y estudio', 'Electrónica', 16, TRUE),
  (98, 'Cámara web 2K Pro', 1129, 'Cámara web de alta nitidez para streaming y reuniones', 'Electrónica', 14, TRUE),
  (99, 'Cámara web 2K Max', 1249, 'Cámara web avanzada con captura fluida y enfoque estable', 'Electrónica', 12, TRUE),
  (100, 'Cámara web 2K X', 1379, 'Cámara web premium con excelente calidad para creadores', 'Electrónica', 10, TRUE),
  (101, 'Foco inteligente Lite', 229, 'Foco inteligente con control remoto desde aplicación móvil', 'Electrónica', 36, TRUE),
  (102, 'Foco inteligente Plus', 269, 'Foco inteligente con escenas de iluminación y temporizador', 'Electrónica', 34, TRUE),
  (103, 'Foco inteligente Pro', 309, 'Foco con automatización para espacios conectados', 'Electrónica', 32, TRUE),
  (104, 'Foco inteligente Max', 349, 'Foco premium con mejor intensidad y control por voz', 'Electrónica', 30, TRUE),
  (105, 'Foco inteligente X', 389, 'Foco inteligente avanzado para ecosistemas de hogar digital', 'Electrónica', 28, TRUE),
  (106, 'Cámara de seguridad Lite', 1099, 'Cámara de seguridad para monitoreo doméstico básico', 'Electrónica', 18, TRUE),
  (107, 'Cámara de seguridad Plus', 1199, 'Cámara con mejor resolución para vigilancia interior', 'Electrónica', 16, TRUE),
  (108, 'Cámara de seguridad Pro', 1329, 'Cámara inteligente para supervisión remota y alertas', 'Electrónica', 14, TRUE),
  (109, 'Cámara de seguridad Max', 1459, 'Cámara de alto desempeño con visión mejorada', 'Electrónica', 12, TRUE),
  (110, 'Cámara de seguridad X', 1589, 'Cámara premium con conectividad estable y grabación clara', 'Electrónica', 10, TRUE),
  (111, 'Timbre inteligente Lite', 899, 'Timbre inteligente con notificaciones y vista remota', 'Electrónica', 16, TRUE),
  (112, 'Timbre inteligente Plus', 999, 'Timbre digital con mejor ángulo de visión', 'Electrónica', 14, TRUE),
  (113, 'Timbre inteligente Pro', 1099, 'Timbre inteligente para control de acceso en el hogar', 'Electrónica', 12, TRUE),
  (114, 'Timbre inteligente Max', 1199, 'Timbre avanzado con respuesta rápida y mejor audio', 'Electrónica', 10, TRUE),
  (115, 'Timbre inteligente X', 1299, 'Timbre premium para entradas conectadas y seguras', 'Electrónica', 8, TRUE),
  (116, 'Cargador inalámbrico Lite', 279, 'Base de carga inalámbrica para teléfonos compatibles', 'Electrónica', 30, TRUE),
  (117, 'Cargador inalámbrico Plus', 329, 'Cargador inalámbrico con mejor estabilidad de carga', 'Electrónica', 28, TRUE),
  (118, 'Cargador inalámbrico Pro', 379, 'Base de carga rápida para smartphone y audífonos', 'Electrónica', 26, TRUE),
  (119, 'Cargador inalámbrico Max', 429, 'Cargador premium con diseño compacto y eficiente', 'Electrónica', 24, TRUE),
  (120, 'Cargador inalámbrico X', 479, 'Cargador avanzado para escritorios y mesas de noche', 'Electrónica', 22, TRUE),
  (121, 'Base de enfriamiento Lite', 359, 'Base de enfriamiento para laptop con ventilación silenciosa', 'Electrónica', 24, TRUE),
  (122, 'Base de enfriamiento Plus', 429, 'Base para laptop con mejor flujo de aire y soporte estable', 'Electrónica', 22, TRUE),
  (123, 'Base de enfriamiento Pro', 499, 'Base de enfriamiento para equipos portátiles exigentes', 'Electrónica', 20, TRUE),
  (124, 'Base de enfriamiento Max', 569, 'Base premium con mayor cobertura y mejor soporte', 'Electrónica', 18, TRUE),
  (125, 'Base de enfriamiento X', 639, 'Base avanzada para laptops con jornadas intensivas', 'Electrónica', 16, TRUE),
  (126, 'Repetidor WiFi Lite', 549, 'Repetidor WiFi para extender señal en espacios interiores', 'Electrónica', 20, TRUE),
  (127, 'Repetidor WiFi Plus', 619, 'Extensor de señal con mejor estabilidad de conexión', 'Electrónica', 18, TRUE),
  (128, 'Repetidor WiFi Pro', 689, 'Repetidor para hogares y oficinas con varios dispositivos', 'Electrónica', 16, TRUE),
  (129, 'Repetidor WiFi Max', 759, 'Extensor de red con mejor alcance y desempeño', 'Electrónica', 14, TRUE),
  (130, 'Repetidor WiFi X', 829, 'Repetidor premium para cobertura inalámbrica más amplia', 'Electrónica', 12, TRUE),
  (131, 'Disco duro externo 1TB Lite', 999, 'Disco duro externo de 1TB para respaldo cotidiano', 'Electrónica', 22, TRUE),
  (132, 'Disco duro externo 1TB Plus', 1089, 'Unidad externa para almacenamiento y transporte de archivos', 'Electrónica', 20, TRUE),
  (133, 'Disco duro externo 1TB Pro', 1179, 'Disco duro externo confiable para oficina y estudio', 'Electrónica', 18, TRUE),
  (134, 'Disco duro externo 1TB Max', 1269, 'Almacenamiento portátil para información de gran volumen', 'Electrónica', 16, TRUE),
  (135, 'Disco duro externo 1TB X', 1359, 'Unidad premium con mejor desempeño y diseño resistente', 'Electrónica', 14, TRUE),
  (136, 'Memoria microSD 128GB Lite', 249, 'Memoria microSD para ampliar almacenamiento en dispositivos', 'Electrónica', 34, TRUE),
  (137, 'Memoria microSD 128GB Plus', 289, 'Memoria rápida para fotos, video y aplicaciones móviles', 'Electrónica', 32, TRUE),
  (138, 'Memoria microSD 128GB Pro', 329, 'Tarjeta de memoria con mayor velocidad para uso continuo', 'Electrónica', 30, TRUE),
  (139, 'Memoria microSD 128GB Max', 369, 'Memoria premium para grabación y transferencia confiable', 'Electrónica', 28, TRUE),
  (140, 'Memoria microSD 128GB X', 409, 'Tarjeta de memoria avanzada para múltiples dispositivos', 'Electrónica', 26, TRUE),
  (141, 'Soporte de monitor Lite', 499, 'Soporte para monitor que mejora la organización del escritorio', 'Electrónica', 18, TRUE),
  (142, 'Soporte de monitor Plus', 569, 'Base para monitor con mejor ajuste y estabilidad', 'Electrónica', 16, TRUE),
  (143, 'Soporte de monitor Pro', 639, 'Soporte ergonómico para estaciones de trabajo modernas', 'Electrónica', 14, TRUE),
  (144, 'Soporte de monitor Max', 709, 'Soporte de alto desempeño para pantallas de uso continuo', 'Electrónica', 12, TRUE),
  (145, 'Soporte de monitor X', 779, 'Soporte premium para monitor con diseño robusto', 'Electrónica', 10, TRUE),
  (146, 'Aro de luz LED Lite', 399, 'Aro de luz LED para videollamadas, foto y contenido digital', 'Electrónica', 24, TRUE),
  (147, 'Aro de luz LED Plus', 469, 'Aro de luz con mejor intensidad y ajuste simple', 'Electrónica', 22, TRUE),
  (148, 'Aro de luz LED Pro', 539, 'Iluminación LED uniforme para streaming y grabación', 'Electrónica', 20, TRUE),
  (149, 'Aro de luz LED Max', 609, 'Aro de luz avanzado para estudios y creadores', 'Electrónica', 18, TRUE),
  (150, 'Aro de luz LED X', 679, 'Iluminación premium con mejor difusión y control', 'Electrónica', 16, TRUE),
  (151, 'Control gamer inalámbrico Lite', 699, 'Control inalámbrico para juegos casuales y entretenimiento', 'Electrónica', 20, TRUE),
  (152, 'Control gamer inalámbrico Plus', 779, 'Control con mejor agarre y conectividad estable', 'Electrónica', 18, TRUE),
  (153, 'Control gamer inalámbrico Pro', 859, 'Control avanzado para sesiones intensivas de juego', 'Electrónica', 16, TRUE),
  (154, 'Control gamer inalámbrico Max', 939, 'Control premium con respuesta precisa y diseño ergonómico', 'Electrónica', 14, TRUE),
  (155, 'Control gamer inalámbrico X', 1019, 'Control de alto desempeño para consolas y PC compatibles', 'Electrónica', 12, TRUE),
  (156, 'Teclado gamer mecánico Lite', 799, 'Teclado gamer mecánico para entrada rápida y precisa', 'Electrónica', 18, TRUE),
  (157, 'Teclado gamer mecánico Plus', 889, 'Teclado con iluminación y mejor respuesta para gaming', 'Electrónica', 16, TRUE),
  (158, 'Teclado gamer mecánico Pro', 979, 'Teclado mecánico de alto desempeño para jugadores exigentes', 'Electrónica', 14, TRUE),
  (159, 'Teclado gamer mecánico Max', 1069, 'Teclado premium con construcción sólida y switches precisos', 'Electrónica', 12, TRUE),
  (160, 'Teclado gamer mecánico X', 1159, 'Teclado gamer avanzado para sesiones prolongadas', 'Electrónica', 10, TRUE),
  (161, 'Mouse gamer ultraligero Lite', 549, 'Mouse gamer ultraligero con sensor preciso para juego rápido', 'Electrónica', 22, TRUE),
  (162, 'Mouse gamer ultraligero Plus', 629, 'Mouse gamer con mejor respuesta y diseño cómodo', 'Electrónica', 20, TRUE),
  (163, 'Mouse gamer ultraligero Pro', 709, 'Mouse de precisión para sesiones competitivas en PC', 'Electrónica', 18, TRUE),
  (164, 'Mouse gamer ultraligero Max', 789, 'Mouse premium con deslizamiento suave y buen control', 'Electrónica', 16, TRUE),
  (165, 'Mouse gamer ultraligero X', 869, 'Mouse avanzado para jugadores que buscan velocidad y exactitud', 'Electrónica', 14, TRUE),
  (166, 'Audífonos inalámbricos Lite', 479, 'Audífonos inalámbricos para música, llamadas y uso diario', 'Electrónica', 28, TRUE),
  (167, 'Audífonos inalámbricos Plus', 559, 'Audífonos con mejor autonomía y sonido más limpio', 'Electrónica', 26, TRUE),
  (168, 'Audífonos inalámbricos Pro', 639, 'Audífonos Bluetooth para oficina, estudio y entretenimiento', 'Electrónica', 24, TRUE),
  (169, 'Audífonos inalámbricos Max', 719, 'Audífonos premium con mejor ajuste y experiencia de audio', 'Electrónica', 22, TRUE),
  (170, 'Audífonos inalámbricos X', 799, 'Audífonos avanzados con conectividad estable y diseño moderno', 'Electrónica', 20, TRUE),
  (171, 'Cámara deportiva Lite', 1399, 'Cámara deportiva para grabar actividades y recorridos al aire libre', 'Electrónica', 14, TRUE),
  (172, 'Cámara deportiva Plus', 1529, 'Cámara de acción con mejor estabilidad de imagen', 'Electrónica', 12, TRUE),
  (173, 'Cámara deportiva Pro', 1659, 'Cámara deportiva resistente para grabación en movimiento', 'Electrónica', 10, TRUE),
  (174, 'Cámara deportiva Max', 1789, 'Cámara de acción premium para contenido dinámico', 'Electrónica', 9, TRUE),
  (175, 'Cámara deportiva X', 1919, 'Cámara avanzada con captura fluida y diseño compacto', 'Electrónica', 8, TRUE),
  (176, 'Mini dron Lite', 1699, 'Mini dron recreativo con control sencillo y vuelo estable', 'Electrónica', 12, TRUE),
  (177, 'Mini dron Plus', 1849, 'Dron compacto con mejor autonomía para tomas casuales', 'Electrónica', 11, TRUE),
  (178, 'Mini dron Pro', 1999, 'Dron portátil con mejor maniobrabilidad y respuesta', 'Electrónica', 10, TRUE),
  (179, 'Mini dron Max', 2149, 'Dron de alto desempeño para capturas aéreas recreativas', 'Electrónica', 9, TRUE),
  (180, 'Mini dron X', 2299, 'Dron premium con mejor estabilidad y control inteligente', 'Electrónica', 8, TRUE),
  (181, 'Proyector LED Lite', 2399, 'Proyector LED para presentaciones y cine en casa', 'Electrónica', 12, TRUE),
  (182, 'Proyector LED Plus', 2549, 'Proyector con mejor brillo y definición para interiores', 'Electrónica', 11, TRUE),
  (183, 'Proyector LED Pro', 2699, 'Proyector de alto rendimiento para oficina y entretenimiento', 'Electrónica', 10, TRUE),
  (184, 'Proyector LED Max', 2849, 'Proyector premium con mejor contraste y conectividad', 'Electrónica', 9, TRUE),
  (185, 'Proyector LED X', 2999, 'Proyector avanzado para uso multimedia y profesional', 'Electrónica', 8, TRUE),
  (186, 'Regleta inteligente Lite', 399, 'Regleta inteligente para conectar y proteger equipos electrónicos', 'Electrónica', 24, TRUE),
  (187, 'Regleta inteligente Plus', 469, 'Regleta con mejor distribución de energía y control práctico', 'Electrónica', 22, TRUE),
  (188, 'Regleta inteligente Pro', 539, 'Regleta para escritorios y espacios de trabajo conectados', 'Electrónica', 20, TRUE),
  (189, 'Regleta inteligente Max', 609, 'Regleta premium con mejor protección y diseño robusto', 'Electrónica', 18, TRUE),
  (190, 'Regleta inteligente X', 679, 'Regleta avanzada para estaciones electrónicas modernas', 'Electrónica', 16, TRUE),
  (191, 'Adaptador multipuerto Lite', 449, 'Adaptador multipuerto para ampliar conexiones en laptops', 'Electrónica', 22, TRUE),
  (192, 'Adaptador multipuerto Plus', 519, 'Adaptador con puertos adicionales para oficina y movilidad', 'Electrónica', 20, TRUE),
  (193, 'Adaptador multipuerto Pro', 589, 'Adaptador compacto para video, datos y periféricos', 'Electrónica', 18, TRUE),
  (194, 'Adaptador multipuerto Max', 659, 'Adaptador de alto desempeño para estaciones de trabajo', 'Electrónica', 16, TRUE),
  (195, 'Adaptador multipuerto X', 729, 'Adaptador premium para productividad y conectividad extendida', 'Electrónica', 14, TRUE),
  (196, 'Soporte para tablet Lite', 289, 'Soporte ajustable para tablet en escritorio o mostrador', 'Electrónica', 26, TRUE),
  (197, 'Soporte para tablet Plus', 339, 'Base para tablet con mejor estabilidad y ajuste cómodo', 'Electrónica', 24, TRUE),
  (198, 'Soporte para tablet Pro', 389, 'Soporte funcional para tablet en trabajo, estudio y atención al cliente', 'Electrónica', 22, TRUE),
  (199, 'Soporte para tablet Max', 439, 'Soporte premium para tablet con mejor sujeción y acabado', 'Electrónica', 20, TRUE),
  (200, 'Soporte para tablet X', 489, 'Soporte avanzado para tablet pensado para uso continuo', 'Electrónica', 18, TRUE)
ON CONFLICT (id) DO UPDATE SET
  nombre = EXCLUDED.nombre,
  precio = EXCLUDED.precio,
  descripcion = EXCLUDED.descripcion,
  categoria = EXCLUDED.categoria,
  stock = EXCLUDED.stock,
  activo = EXCLUDED.activo;

SELECT setval('productos_id_seq', (SELECT MAX(id) FROM productos));
